### ISSUE TITLE
【求助】运行yarn run lint, 报错ESLint couldn't find the plugin "@typescript-eslint/eslint-plugin"

### ISSUE THREAD

**Issue by niexq** [umijs/fabric#116]
## 本地运行 或 使用github actions 跑ci
```bash
 yarn run lint
```
### 报错

![](https://raw.githubusercontent.com/niexq/picbed/main/picgo/eslinterror.png)

### 复现仓库地址：
https://github.com/niexq/react-auto-sizer

### ci报错地址：
https://github.com/niexq/react-auto-sizer/runs/4252690944?check_suite_focus=true
![](https://raw.githubusercontent.com/niexq/picbed/main/picgo/cierror.png)

### 环境

"@umijs/fabric": "^2.8.1"

yarn 1.22.4

node v12.18.4

MacBook Pro (15-inch, 2018)

**Comment by niexq** [comment]
@chenshuai2144 大佬，
参考ant-design/pro-components项目中依赖@umijs/fabric，也没有额外依赖@typescript-eslint/eslint-plugin等插件。

但确实ant-design/pro-components本地执行yarn（及时删除yarn.lock，也是正常的），@typescript-eslint/eslint-plugin是可以被安装在最外层node_modules的，求解？

**Comment by chenshuai2144** [comment]
默认yarn 是打平的。你是不是用了比较高的版本？

**Comment by niexq** [comment]
> 默认yarn 是打平的。你是不是用了比较高的版本？

是的，但很奇怪的是，@umijs/fabric的依赖没有打平在最外层node_modules，包括@umijs/fabric里面的node_modules也没安装上，那我降降版本试试吧，谢谢。

**Comment by chenshuai2144** [comment]
yarn 和npm 新版本改动都很激进，我锁包好久了

**Comment by niexq** [comment]
> yarn 和npm 新版本改动都很激进，我锁包好久了

感谢大佬提点，本地 ```eslint``` 依赖 ```8.*``` 降为 ```7.*``` 正常了 🍻
