### ISSUE TITLE
@umijs/fabric/dist/eslint  缺失依赖包

### ISSUE THREAD

**Issue by panyushan-jade** [umijs/fabric#126]
eslintrc.js
![image](https://user-images.githubusercontent.com/48422428/161042731-f176340b-2cbd-4494-9aeb-b729f767f771.png)
每次执行eslint检查会报@umijs/fabric 找不到对应的依赖
![28a81ab8ab59c835e891dedecf46e14](https://user-images.githubusercontent.com/48422428/161042931-d945920a-61d5-414a-813c-272e941f09b6.png)
使用yarn add  安装对应找不到的依赖包时，又会报别的依赖包找不到

**Comment by Lsnsh** [comment]
删除 `lock` 文件和 `node_modules`，再重新安装试试

**Comment by panyushan-jade** [comment]
> 

已解决，是我开了代理工具 install就会有问题
