### ISSUE TITLE
[BUG]在格式化vue文件中的less样式代码时如果有注释就会将less代码格式化错误

### ISSUE THREAD

**Issue by coderFuYu** [umijs/fabric#128]
package.json
```   json
{ 
 "dependencies":{
    "@umijs/fabric": "^2.10.2",
    "prettier": "^2.6.2",
},
 "scripts": {
    "prettier": "prettier -c --write \"src/**/*\""
  }
}
```

.prettierrc.js
```js
const fabric = require('@umijs/fabric')

module.exports = {
  ...fabric.prettier,
  semi: false
}

```

格式化之前
![image](https://user-images.githubusercontent.com/42110911/163330381-df8e2ac1-8252-4536-8aae-41440b0729b0.png)

格式化之后
![image](https://user-images.githubusercontent.com/42110911/163330308-11e22e01-a9cc-44d8-bf57-84dac99e90ca.png)

**Comment by yunsii** [comment]
在 .vue 中使用的 less？那这个应该是 prettier 还不支持

**Comment by coderFuYu** [comment]
经测试，less代码中出现padding属性和注释时就会出现问题（包括注释padding），应该是prettier的bug，先关闭
