### ISSUE TITLE
npm仅安装此包时无效

### ISSUE THREAD

**Issue by islizeqiang** [umijs/fabric#34]
用npm仅仅安装@umijs/fabric包时，如果没有typescript包则不生效

**Comment by maxborts** [comment]
> 用npm仅仅安装@umijs/fabric包时，如果没有typescript包则不生效

我也遇到了,需要  yarn -D add typescript

**Comment by chenshuai2144** [comment]
来个 pr 丰富一下 readme?

**Comment by islizeqiang** [comment]
> 来个 pr 丰富一下 readme?

已提

**Comment by chenshuai2144** [comment]
@islizeqiang  非常感谢
