### ISSUE TITLE
Configuration for rule "import/no-cycle" is invalid: Value null should be integer.

### ISSUE THREAD

**Issue by RihuaChen** [umijs/fabric#46]
> This is indeed a bug in eslint v7.3.0; downgrade to v7.2 for now.

[eslint-issue](https://github.com/airbnb/javascript/issues/2227)

ESLint 7.3.0 has some issue here, but when I downgrade to v7.2 

It will cause another issue, first it will @types-eslint issue, I install it then it will cause

> ESLint couldn't find the plugin "eslint-plugin-eslint-comments".

(The package "eslint-plugin-eslint-comments" was not found when loaded as a Node module from the directory "/Users/crh/Project/za-prudential-thai".)

Then it will cause another issue...

I think maybe we can stay in a stable version first.

**Comment by chenshuai2144** [comment]
升级最新的 eslint 吧

**Comment by yingzhiji** [comment]
时不时会出现这个问题，用的一直是最新版的 eslint，不知道是不是 eslint 的问题
