### ISSUE TITLE
版本是不是发错顺序了，导致commit不了。

### ISSUE THREAD

**Issue by kaoding** [umijs/fabric#48]
umi3 中使用 yarn  create @umijs/umi-app
和
antd pro 中使用 yarn create umi my-app
今天使用都有问题，前天还是好的。

**Comment by joesdu** [comment]
我也感觉这个版本号奇葩的一匹.都不知道用哪个了.

**Comment by hankaibo** [comment]
package.json中是2.2.0，但另一个地方是2.0.11，肯定有问题，请作者修复一下。

**Comment by chenshuai2144** [comment]
为了修复 2.0.11 的，又发了 一下。安装还是 2.20 的

**Comment by joesdu** [comment]
> 为了修复 2.0.11 的，又发了 一下。安装还是 2.20 的

应该是需要将版本号升的比2.20还高才行,不然npm或者yarn以为2.2才是最新的.
