### ISSUE TITLE
升级到2.2.2后，执行eslint特别慢

### ISSUE THREAD

**Issue by areyouse7en** [umijs/fabric#56]
升级到2.2.2后，执行eslint就变得特别慢，打开debug后看到，每次loading package.json要花3s以上，processing 一个tsx文件也要4s以上，整个项目执行下来十几分钟都还没结束
![image](https://user-images.githubusercontent.com/3938443/87505882-937f1b00-c69c-11ea-897c-2e8120e6cdc2.png)

不知是不是跟这个版本增加了tsconfig.json的读取有关

**Comment by zhinanchendd01** [comment]
同样是非常慢，还在找原因

**Comment by chenshuai2144** [comment]
你们猜的是对的，就是因为加了 ts-loader

**Comment by mastercbhw** [comment]
@chenshuai2144  可以回退到那一个版本呐，确实好慢

**Comment by chenshuai2144** [comment]
在根目录搞个tsconfig.json就快了 

Ts官方不愿意改 只能适应他们了
