### ISSUE TITLE
@typescript-eslint/camelcase

### ISSUE THREAD

**Issue by jefferyssy** [umijs/fabric#57]
在新的 typescript-eslint 中 camelcase 被删除了  这边还是引用 vscode就报错了

**Comment by jefferyssy** [comment]
Definition for rule '@typescript-eslint/camelcase' was not foundeslint(@typescript-eslint/camelcase)

**Comment by shihongchun** [comment]
> Definition for rule '@typescript-eslint/camelcase' was not foundeslint(@typescript-eslint/camelcase)

兄弟，你是怎么解决的
