### ISSUE TITLE
2.3.0 @typescript-eslint/no-unused-vars false positive

### ISSUE THREAD

**Issue by ttys026** [umijs/fabric#60]
![image](https://user-images.githubusercontent.com/19804057/96670008-03362d80-1391-11eb-85e5-1ede4b6b5a86.png)
升级到 2.3.0 后引用的类型一定会报 unused 的错误，但实际上使用了。2.2.2 版本是好的

**Comment by chenshuai2144** [comment]
升级一下 ts@4
