### ISSUE TITLE
Unexpected character '@' 语法无法识别

### ISSUE THREAD

**Issue by heran** [umijs/fabric#78]
.\src\pages\login\index.jsx
  11:1  error  Parsing error: Unexpected character '@'

✖ 1 problem (1 error, 0 warnings)

` 
@connect(({ dispatch, userLogin }) => ({   dispatch,   userLogin }))
 class Index extends PureComponent {}
`

**Comment by chenshuai2144** [comment]
看起来是解析器的问题。但是测试用例里也有没有问题

**Comment by iamiota** [comment]
降级回2.0.8没有这个错误了

**Comment by chenshuai2144** [comment]
修复了一下，可能升级到最新版本
