### ISSUE TITLE
当使用tnpm安装依赖, vscode的eslint对ts文件不提示

### ISSUE THREAD

**Issue by ananiy** [umijs/fabric#83]
详细请看图, 第一张图是用tnpm直接装依赖, 左下角的ts文件没有提示
第二张图切换了npm mode安装依赖, 左下角的ts文件有提示

![111](https://user-images.githubusercontent.com/33290601/105939889-11cd6880-6095-11eb-9bb4-ab8ebe6cb2aa.png)
![222](https://user-images.githubusercontent.com/33290601/105939892-142fc280-6095-11eb-9fd8-8a7eca387d33.png)

附上demo文件
[demo.zip](https://github.com/umijs/fabric/files/5877599/demo.zip)

另外, 在新的vue3项目中, 用tnpm安装依赖也没有问题
![image](https://user-images.githubusercontent.com/33290601/105940138-94562800-6095-11eb-832e-d67a918ea6cb.png)

**Comment by liangjiayu** [comment]
npm正常提示，但是tnpm安装依赖的话，vscode的eslint插件就有问题，无法正常提示错误，这种依赖包和vscode插件的问题，实在难以排查😫😫😫

**Comment by ananiy** [comment]
原因是tnpm装完的包名不符合vscode-eslint插件的检测, 详见: https://github.com/microsoft/vscode-eslint/issues/1270#issuecomment-853735585

配置一下插件强制开始ts文件的检测就行....

```json
{
  "eslint.validate": [
    "javascript",
    "javascriptreact",
    "typescript",
    "typescriptreact",
    "vue"
  ],
}
```

**Comment by liangjiayu** [comment]
> 原因是tnpm装完的包名不符合vscode-eslint插件的检测, 详见: [microsoft/vscode-eslint#1270 (comment)](https://github.com/microsoft/vscode-eslint/issues/1270#issuecomment-853735585)
> 
> 配置一下插件强制开始ts文件的检测就行....
> 
> ```json
> {
>   "eslint.validate": [
>     "javascript",
>     "javascriptreact",
>     "typescript",
>     "typescriptreact",
>     "vue"
>   ],
> }
> ```

还有其他解决方案吗？ 这样子的话，项目需要公用一份vscode的配置吧
